OLD_PROMPT_COMMAND="$PROMPT_COMMAND"
PROMPT_COMMAND="_MO_prompt_command;$PROMPT_COMMAND"

unregister_MO() {
    PROMPT_COMMAND="$OLD_PROMPT_COMMAND"
    unset OLD_PROMPT_COMMAND
    unset -f unregister_MO
}
